name: Flask application

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        docker login -u "shalinitiwari2701" --password-Varun@12345
        docker image build -t shalinitiwari2701/flaskupdate:latest .
        docker shalinitiwari2701/flaskupdate:latest
