name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and Pushing the Docker image
      run: |
         echo "${{ secrets.DOCKERKEY}}" | docker login --username "shalinitiwari2701" --password-stdin
         docker build -t shalinitiwari2701/dockerimage .
         docker push shalinitiwari2701/dockerimage:latest
